# Dependencies
gems:             [jekyll-paginate]


# Permalinks
permalink:        pretty

# Setup
title:            F.i.d.T
tagline:          '<b>F</b>uß <b>i</b>n <b>d</b>er <b>T</b>ür - Jetzt reden wir mit unseren Leser/innen.'
description:      'Erdacht auf dem <a href="https://www.facebook.com/facebookjournalismproject">Facebook Journalism Project</a> Hackathon in Hamburg, Juni 2017.'
url:              https://github.com/dpa-newslab/fidt
baseurl:          /fidt/

author:
  name:           'Team F.i.d.T' 
  url:            https://www.facebook.com/groups/1888079458098823

paginate:         15 

# Custom vars
version:          2.1.0
github:           https://github.com/dpa-newslab/fidt

