
mermaidAPI.min.js :
	wget https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaidAPI.js

jquery-3.1.1.min.js:
	wget https://code.jquery.com/jquery-3.1.1.min.js

mermaid.min.js: 
	wget https://cdn.rawgit.com/knsv/mermaid/6.0.0/dist/mermaid.js
